error: Implement error queue
Reporting an error via kelpo_error() no longer overwrites the
previously-reported error but instead appends the new error into a
queue.

The functionality of kelpo_error_code() was changed to return and remove
the most recent entry in the error queue.