error: Add ability to set custom error callback function
This callback gets called every time kelpo_report_error() is called;
i.e. every time Kelpo reports an error.